### ISSUE TITLE
Suggestion/Feature Request: Include Snowpack in the Comparison

### ISSUE THREAD

**Issue by bjesuiter** [GoogleChromeLabs/tooling.report#411] opened 2021-02-05 10:47 UTC
I would like to have Snowpack included on this page. 

https://www.snowpack.dev/

I started using snowpack for building my chrome extension output, which is awesome due to snowpack being easy to configure for multi-entry point builds (e.g. not building one website or so, but mutliple folders, one for background service worker, one for options page and so on.) 

It also ships only modern es modules if possible, but for legacy they added native bundling features to snowpack recently. 

So, thank you for consideration! :)

**Comment by jakearchibald** [comment] 2021-02-05 10:54
Dupe of https://github.com/GoogleChromeLabs/tooling.report/issues/352

**Closed as completed by jakearchibald** 2021-02-05 10:54 UTC
